### ISSUE TITLE
Fabric is currently 1.2.0. Could you please update the pod?

### ISSUE THREAD

**Issue by GorkaMM** [zergtmn/Fabric#1]

**Comment by zergtmn** [comment]
Hi. I did a quick check and I think the pod contains the latest frameworks available through the Fabric app at the moment. Version number of the pod 1.1.1 matches the version number of Fabric.framework in the repo. Where have you seen the version 1.2.0?

**Comment by GorkaMM** [comment]
I'm sorry, I thought the 1.2.0 version was related to Fabric framework itself. It's all ok then. Thank you for your fast response and sorry for the misunderstanding!
