### ISSUE TITLE
Accounts & Social frameworks are not linked...

### ISSUE THREAD

**Issue by RyanCopley** [zergtmn/Fabric#11]
Using 1.2.1...

    Undefined symbols for architecture x86_64:
    "_ACAccountTypeIdentifierTwitter", referenced from:
    +[TWTTRAuthenticator saveToiOSAccountStoreWithAuthToken:secret:userName:] in TwitterKit(TWTTRAuthenticator.o)
    -[TWTTRAppleSocialAuthenticaticationProvider requestAccessForTwitterAccountsWithCompletion:] in TwitterKit(TWTTRAppleSocialAuthenticaticationProvider.o)
    -[TWTTRAppleSocialAuthenticaticationProvider getTwitterAccounts] in TwitterKit(TWTTRAppleSocialAuthenticaticationProvider.o)
    "_OBJC_CLASS_$_ACAccount", referenced from:
    objc-class-ref in TwitterKit(TWTTRAuthenticator.o)
    "_OBJC_CLASS_$_ACAccountCredential", referenced from:
    objc-class-ref in TwitterKit(TWTTRAuthenticator.o)
    "_OBJC_CLASS_$_ACAccountStore", referenced from:
    objc-class-ref in TwitterKit(TWTTRAuthenticator.o)
    objc-class-ref in TwitterKit(TWTTRAppleSocialAuthenticaticationProvider.o)
    "_OBJC_CLASS_$_SLComposeViewController", referenced from:
    objc-class-ref in TwitterKit(TWTRComposer.o)
    "_OBJC_CLASS_$_SLRequest", referenced from:
    objc-class-ref in TwitterKit(TWTTRAppleSocialAuthenticaticationProvider.o)
    "_SLServiceTypeTwitter", referenced from:
    -[TWTTRAppleSocialAuthenticaticationProvider performTwitterRequestWithURL:parameters:account:completion:] in TwitterKit(TWTTRAppleSocialAuthenticaticationProvider.o)
    -[TWTRComposer init] in TwitterKit(TWTRComposer.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zergtmn** [comment]
I wonder why do you get these build errors although TwitterKit.h already imports all frameworks it needs:
```
//
//  TwitterKit.h
//
//  Copyright (c) 2014 Twitter. All rights reserved.
//

#if __has_feature(modules)
@import AddressBook;
@import Accounts;
@import CoreData;
@import Foundation;
@import Social;
@import UIKit;
#else
#import <AddressBook/AddressBook.h>
#import <Accounts/Accounts.h>
#import <CoreData/CoreData.h>
#import <Foundation/Foundation.h>
#import <Social/Social.h>
#import <UIKit/UIKit.h>
#endif
```

**Comment by RyanCopley** [comment]
Create a new project
Add these Pods:


    pod 'Fabric', '~> 1.2.1'
    pod 'Fabric/Crashlytics', '~> 1.2.1'
    pod 'Fabric/Twitter', '~> 1.2.1'

Do:

     pod install

Try to compile... The errors above are shown, I'm not entirely sure how to fix this but I'm just trying to propose a solution-- right now TwitterKit does not compile at all.

**Comment by zergtmn** [comment]
Ah, I've also experienced this. If you add `#import <TwitterKit/TwitterKit.h>` it should build without any errors. So listing frameworks in podspec would be redundant because they are imported by TwitterKit.h. But I agree that it should also work without #import. I'm just not sure what's causing this.

**Comment by RyanCopley** [comment]
Ahh you're importing it via code... odd, at minimum could you please add a disclaimer? It makes the library look broken for people just getting started. I typically add the pod to my Podfile, pod install, then compile, to make sure the pod works first, and this kills confidence.
