### ISSUE TITLE
./Fabric.framework/run YOUR_API_KEY YOUR_BUILD_SECRET

### ISSUE THREAD

**Issue by manishkumarv2** [zergtmn/Fabric#14]
While configuring from Terminal i am getting following message
./Fabric.framework/run YOUR_API_KEY YOUR_BUILD_SECRET

I am providing my "Consumer Key (API Key)" and "Consumer Secret (API Secret)" what i am doing wrong?
Thanks

**Comment by zergtmn** [comment]
I'm not sure where do you get that message from. Please check that you configured Run Script Build Phase correctly. Like here http://www.runscriptbuildphase.com/ but change the path from `./Fabric.framework/run` to `./Pods/Fabric/Fabric.framework/run`
