### ISSUE TITLE
Duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by jeffoleary1987** [zergtmn/Fabric#15]
I'm receiving duplicate symbol errors with the following in the podfile:
    pod 'Fabric', '~> 1.2'
    pod 'Fabric/Crashlytics', '~> 1.2' 
    
There are 304 duplicate symbol errors all complaining because of the following example
/Users/jeffoleary/Documents/{projectDirectory}/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSClientBase.o)
/Users/jeffoleary/Documents/{projectDirectory}/Pods/Fabric/Fabric.framework/Fabric(CLSClientBase.o)

**Comment by rromanchuk** [comment]
related https://twittercommunity.com/t/duplicate-symbols-in-crashlytics-arm64-armv7s-and-armv7/43451
