### ISSUE TITLE
line 2: ./Pods/Fabric/Fabric.framework/run: Permission denied

### ISSUE THREAD

**Issue by frobichaud** [zergtmn/Fabric#16]
After migrating to 1.2.3, we get a permission denied when the script tries to run in post-build script.
The fix is to chmod +x ./Pods/Fabric/Fabric.framework/run

**Comment by zergtmn** [comment]
Fabric.framework/run has its permissions set to 755 in the repository as it should be. If this issue shows up again try reinstalling the pod.

**Comment by yvasileuski** [comment]
Using Fabric (1.2.8) The same issue is still there.
