### ISSUE TITLE
Is YOUR_BUILD_SECRET needed?

### ISSUE THREAD

**Issue by mokagio** [zergtmn/Fabric#17]
Looking at [Fabric's docs](https://dev.twitter.com/crashlytics/ios/advanced-setup) it doesn't look like the build secret is needed. Any reason why it's specified in the README?

**Comment by zergtmn** [comment]
Perhaps YOUR_BUILD_SECRET is optional or become optional in the recent update. It's in the readme because the Fabric app says to pass it.

**Comment by mokagio** [comment]
Fair enough... It's probably some inconsistency with their docs then. Thanks :)
