### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by snakecharmer** [zergtmn/Fabric#20]
The project require as dependency libstdc++.dylib

**Comment by zergtmn** [comment]
This pod doesn't require any dependencies itself. If frameworks need any dependencies they already link them. You just have to `#import` the appropriate module for dependencies to be picked up.

**Comment by snakecharmer** [comment]
Looks like was only a crazy X-Code after cleaning the cache folder everything works. Thanks & Sorry for the wrong issue
