### ISSUE TITLE
[Crashlytics] Version 3.0.8 (50) requires twitter's consumerKey/Secret

### ISSUE THREAD

**Issue by frranck** [zergtmn/Fabric#25]
Hi,
Since i updated to Crashlytics Version 3.0.8, my apps fail at start with:

[Crashlytics] Version 3.0.8 (50)
[Twitter] Cannot find kit info. Try initWithConsumerKey:consumerSecret: instead.
[Twitter] Cannot find kit info. Try initWithConsumerKey:consumerSecret: instead.

**Comment by zergtmn** [comment]
You might need to run Fabric App to reconfigure your project for the new version of Crashlytics or TwitterKit.

**Comment by frranck** [comment]
What will the "Fabric app" do to my project ? I'm using cocoapod there's no reason i use external tools.

**Comment by frranck** [comment]
I removed cocoapods and used the "fabric app". Please use cocoapods, your "fabric app" is ridiculous.
Isn't fabric made for developers?

**Comment by tromg** [comment]
Hi all. i've met the same issue and that's what helped me:
1. Use Fabric.app to configure your project
2. ASSUME THAT IT IS WORKING AS IT SHOULD 
3.  "Replace" fabric.app's frameworks with pods.
4. ????
5. PROFIT!!

**Comment by frranck** [comment]
@tromg yeah, but you'll need to go to step 1 each time your pod get updated... 
#failure

**Comment by fluidsonic** [comment]
We use Crashlytics (and now Fabric) via CocoaPods for a long time now and usually without issues.

- Fabric app is must installed for symbol upload (but no need to configure the project with it)
- App needs a Run Script Phase: `./Pods/Fabric/Fabric.framework/run <api key> <build secret>`
- You can find API key & secret here: https://fabric.io/settings/organizations > Your organization  
There are two links at the top below the organization name: "API Key" & "Build Secret"
- Podfile is like that:
```
pod 'Fabric', '1.3.0'
pod 'Fabric/Crashlytics','1.3.0'
```
