### ISSUE TITLE
Xcode 7: Include of non-modular header inside framework module 'Crashlytics'

### ISSUE THREAD

**Issue by jshier** [zergtmn/Fabric#27]
I'm this error intermittently:

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Crashlytics.h"
        ^
/Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/Crashlytics.h:10:9: error: include of non-modular header inside framework module 'Crashlytics'
#import <Fabric/FABAttributes.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Crashlytics.h"
        ^
/Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/Crashlytics.h:11:9: note: in file included from /Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/Crashlytics.h:11:
#import "CLSLogging.h"
        ^
/Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/CLSLogging.h:8:9: error: include of non-modular header inside framework module 'Crashlytics'
#import <Fabric/FABAttributes.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Crashlytics.h"
        ^
/Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/Crashlytics.h:12:9: note: in file included from /Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/Crashlytics.h:12:
#import "CLSReport.h"
        ^
/Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/CLSReport.h:9:9: error: include of non-modular header inside framework module 'Crashlytics'
#import <Fabric/FABAttributes.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Crashlytics.h"
        ^
/Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/Crashlytics.h:13:9: note: in file included from /Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/Crashlytics.h:13:
#import "CLSStackFrame.h"
        ^
/Users/jshier/Desktop/project/Pods/Fabric/Crashlytics.framework/Headers/CLSStackFrame.h:9:9: error: include of non-modular header inside framework module 'Crashlytics'
#import <Fabric/FABAttributes.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Crashlytics'
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/jshier/Desktop/project/Pods/Fabric/Fabric.framework/Headers/Fabric.h"
```

Enabling non-modular includes doesn't help. Perhaps exporting the module maps included with the frameworks in the podspec would help? What is odd is that this is for my test target, not my main target, which works fine.

**Comment by jshier** [comment]
We're actually also seeing this issue with Xcode 6.3.2, why trying to build a project for iOS 7.1 using libraries. Previously the project used frameworks through CocoaPods and worked fine.

**Comment by medington** [comment]
I'm also running into this error with Xcode 6.4, when using the latest Fabric / Crashlytics 3.0.11 (current as of this post). The very strange thing is this error shows up **only** when building with a Jenkins job. Compilation from Xcode or from xcodebuild with the same command line works absolutely fine on the same computer with the same files! Anyway, I will post a follow-up here if and when I get it sorted out. 

Oh I should also add that compiling with Crashlytics 2 doesn't have this problem. Podfile has entries for Fabric and Crashlytics only with no version specifier. It seems today that Twitter took over the podspec and removed the ability to compile against 2.0 though.

**Comment by kunass2** [comment]
Exactly The same issue with Fabric and Crashlytics installed via Pods on Xcode 7 beta 3.

**Comment by adamjack** [comment]
I have the same issue on a new install on latest (non-beta) Xcode.

**Comment by davetroy** [comment]
I am seeing this with a test target using latest Crashlytics on Xcode 7 beta 5. Any suggestions appreciated.

**Comment by davetroy** [comment]
I was able to get around it by excluding the Fabric and Crashlytics pods from my test target:

````
target :AppTarget, exclusive: true do
  pod 'Fabric'
  pod 'Crashlytics'
end
````

This strikes me as not ideal; an actual fix would be great! Thanks.

**Comment by zergtmn** [comment]
@davetroy If you want this issue to get fixed you should consider reporting it to the Fabric team. I know that cocoapods.org page still points to this repo but I'm not affiliated with them in any way.

**Comment by davetroy** [comment]
Thanks!
