### ISSUE TITLE
removing dependency on fabric app

### ISSUE THREAD

**Issue by jlnbuiles** [zergtmn/Fabric#3]
would it be possible to get this pod to work without the need of the fabric app/plug-in?

after successfully downloading the pods and attempting to build the project, im getting the following error:

Fabric: This app relies on Fabric. Please sign up for access at https://fabric.io/sign_up,
install Fabric.app then ask a team member to invite you to this app's organization.

If this machine is a build server please remove Fabric.app if present and use xcodebuild so that SchoolSpring.app.dSYM is uploaded.
Command /bin/sh failed with exit code 1

**Comment by zergtmn** [comment]
Well if Fabric.framework itself relies on Fabric app to upload symbols I doubt we can do anything to stop it.
If you use only Crashlytics in your app try this pod instead https://github.com/bpoplauschi/CrashlyticsFramework

**Comment by jlnbuiles** [comment]
will take a look. thanks!
