### ISSUE TITLE
crashlytics answers not working with pod

### ISSUE THREAD

**Issue by jlnbuiles** [zergtmn/Fabric#4]
i'm not sure if there is a step missing in the configuration outlined in the readme, but when i attempted to configure 'answers' it did not work and was asking me to ensure i was using the latest build and rebuild the project. i looked at the version we're using here and it seems to be up-to-date.

once i configured the framework via the mac app, answers was able to be configured.

**Comment by zergtmn** [comment]
Thank you for report. I'll remove the misleading manual install guide from readme until we have a proper solution.
