### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by db42** [zergtmn/Fabric#5]
Using `pod 'Fabric/Crashlytics'`, I get this build error:
```
duplicate symbol _OBJC_IVAR_$_CLSEventLogFile._fileURL in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSEventLogFile.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSEventLogFile.o)
duplicate symbol _OBJC_METACLASS_$_CLSEventLogFile in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSEventLogFile.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSEventLogFile.o)
duplicate symbol _OBJC_CLASS_$_CLSIcon in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSIcon.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSIcon.o)
duplicate symbol _OBJC_IVAR_$_CLSIcon._data in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSIcon.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSIcon.o)
duplicate symbol _OBJC_IVAR_$_CLSIcon._dataHash in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSIcon.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSIcon.o)
duplicate symbol _OBJC_IVAR_$_CLSIcon._prerendered in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSIcon.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSIcon.o)
duplicate symbol _OBJC_IVAR_$_CLSIcon._size in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSIcon.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSIcon.o)
duplicate symbol _OBJC_METACLASS_$_CLSIcon in:
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Crashlytics.framework/Crashlytics(CLSIcon.o)
    /Users/dushyant/Github/gogovan-client-ios/Pods/Fabric/Fabric.framework/Fabric(CLSIcon.o)
```

**Comment by db42** [comment]
Looks like a temporary local issue.

**Comment by devxoul** [comment]
How did you solve it?

**Comment by db42** [comment]
Earlier, crashlytics required one framework - `Crashlytics.framwork`. Fabric requires two frameworks - `Fabric.framework` and `Crashlytics.framework`. Note that both use different `Crashlytics.framework`. 

Reason for this error is your project is still using old `Crashlytics.framework`. To see if your `Crashlytics.framework` is still, you can use `nm` which is a nifty tool to see symbols in a binary. 
`nm Old-Crashlytics.framework` will reveal same symbols present in `Fabric.framework` and `CrashlyticsKits` symbol will be missing in the list.

**Comment by db42** [comment]
Earlier, crashlytics required one framework - `Crashlytics.framwork`. Fabric requires two frameworks - `Fabric.framework` and `Crashlytics.framework`. Note that both use different `Crashlytics.framework`. 

Reason for this error is your project is still using old `Crashlytics.framework`. To see if your `Crashlytics.framework` is still, you can use `nm` which is a nifty tool to see symbols in a binary. 
`nm Old-Crashlytics.framework` will reveal same symbols present in `Fabric.framework` and `CrashlyticsKits` symbol will be missing in the list.

**Comment by db42** [comment]
Earlier, crashlytics required one framework - `Crashlytics.framwork`. Fabric requires two frameworks - `Fabric.framework` and `Crashlytics.framework`. Note that both use different `Crashlytics.framework`. 

Reason for this error is your project is still using old `Crashlytics.framework`. To see if your `Crashlytics.framework` is still, you can use `nm` which is a nifty tool to see symbols in a binary. 
`nm Old-Crashlytics.framework` will reveal same symbols present in `Fabric.framework` and `CrashlyticsKits` symbol will be missing in the list.

**Comment by devxoul** [comment]
Thanks! It helped me a lot.

**Comment by ctrevarthen** [comment]
I'm still seeing this issue when using the Fabric/Crashlytics pod. Works fine once, but on the second build it fails with duplicate symbols. It looks like the Crashlytics pod is actually being updated automatically when the Fabric "run" script fires - pulling down the latest full Crashlytics.framework, which then has dupes of the CLS* classes with Fabric/Core.

**Comment by Legoless** [comment]
This is still an issue. If you have Fabric Mac app installed this is not a problem. If not, the Crashlytics.framework is modified by Fabric run script and that breaks the build.

**Comment by ctrevarthen** [comment]
@Legoless Thanks for that info. Updating to the Fabric Mac app seems to have resolved the duplicate symbol issue.

**Comment by centurionas** [comment]
Nop, it doesn't help even when using newest Fabric. Even remove and add again via CocoaPods doesn't help. Help! :)

**Comment by ctrevarthen** [comment]
@centurionas Here are the entries I have for my Podfile (needed to include Core, too)

pod 'Fabric/Core', '~> 1.2'
pod 'Fabric/Crashlytics', '~> 1.2'

The Crashlytics run script from XCode:

./Pods/Fabric/Fabric.framework/run YOUR_API_KEY YOUR_API_SECRET

**Comment by centurionas** [comment]
@ctrevarthen Thanks, that helped. I wish they would have normal documentation on CocoaPods pod spec.

**Comment by zergtmn** [comment]
@centurionas we can improve that. Pull requests are welcome.
What was the issue in your case?
There was a breaking change in 1.2 that including `pod 'Fabric', '~> 1.2'` or `pod 'Fabric/Core', '~> 1.2'` is now required for compatibility with CocoaPods 0.36. It's reflected in readme.

**Comment by bassrock** [comment]
I am still getting this error when the build tries to run on my CI.

**Comment by ctrevarthen** [comment]
@bassrock What version of Cocoapods are you using? Can you share your Podfile and the Run Script for Crashlytics from you project's "Build Phases" tab (omitting your API_SECRET and API_KEY)?

**Comment by bassrock** [comment]
Ok I fixed it on the CI. It turns out the apps do something in that in phase. I removed the Fabric and Crashlytics app from the CI and it builds fine now.

**Comment by centurionas** [comment]
I pulled my project source from git on my home's mac and started to get this error again (even I already used @ctrevarthen suggestion and got it working on work's mac). I have cocoapods up to date (0.36), here's my pods file:

pod 'Fabric/Core', '~> 1.2'
pod 'Fabric/Crashlytics', '~> 1.2'

I downloaded newest fabric.app, completely remove crashlytics.app, three times cleaned and deleted build, deleted derived data, performed reset simulator and closed Xcode, but it I'm still getting this annoying error. I'm wondering what happened because previous Crashlytics was working so smoothly and now with Fabric I even don't get uploaded dsyms (even the version is created) and so I need to upload them manually through the hidden link in fabric.io website...

**Comment by centurionas** [comment]
Update: I'v removed fabric two lines from pods, then performed pod install and also removed build run script file and other references in code. Then project started to build successfully (of course). Then I did reset  all the changes from git working copy.... and my project is still building successfully.. :) Any ides?

**Comment by jeffoleary1987** [comment]
any updates on how to resolve the duplicate symbols error?

**Comment by centurionas** [comment]
@jeffoleary1987 Nop, but my suggested "remove&reset" solution worked for my colleague as well :)

**Comment by hananwemotech** [comment]
Hi Every one ,
I have also facing that issue with conflicts in twitterkit and twitter core frameworks stuck in linker error please help me to fix that one 
Thanks in advance .

**Comment by lm2s** [comment]
@hananwemotech verify if you don't have old versions of the .framework inside your project directory. I had this problem and didn't notice that Xcode was loading an old .framework  that was inside the project directory.

**Comment by hananwemotech** [comment]
@lm2s Thanks for your help I really appreciate this for the meanwhile I have fixed that issue with removing the arm64 architecture and it works for me but don't know that apple will accept it or not .
