### ISSUE TITLE
v1.1.3, Crashlytics subspec doesn't work

### ISSUE THREAD

**Issue by jshier** [zergtmn/Fabric#9]
Under the 1.1.3 version of the pod, the Crashlytics subspec doesn't copy the Crashlytics frameworks, so all that's integrated is Fabric.framework. Also, I saw a report on the specs repo that Fabric 1.1.3 may need the AddressBook.framework linked.

**Comment by zergtmn** [comment]
Are you using `use_frameworks`? The pod is currently incompatible with it.
I'm planning to split it into 4 pods: Fabric, Fabric-CrashlyticsKit, Fabric-MoPubKit, Fabric-TwitterKit to get it work with CocoaPods 0.36 and use_frameworks.

**Comment by jshier** [comment]
In both scenarios I don't see the Crashlytics framework. See my latest comment on #8 for a possible direction for the subspecs.
